swagger: '2.0'
info:
  description: External API for Scan Solution
  version: unknown
  title: SimplyConnect Web API
  termsOfService: >-
    In order to access the SimplyConnect Web API you must have written consent
    from Simply Connect HIE. Any other use of this API is prohibited. Please
    contact us.
  contact: {}
host: 'localhost:8081'
basePath: /exchange
schemes:
  - http
  - https

tags:
  - name: scan-sol-controller
    description: Scan Solution Controller

consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /scan-solution/databases:
    get:
      tags:
        - scan-sol-controller
      summary: getDatabasesData
      operationId: getDatabasesDataUsingGET
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolDatabasesDto'
  '/scan-solution/databases/{databaseId}/employees':
    get:
      tags:
        - scan-sol-controller
      summary: getEmployeesData
      operationId: getEmployeesDataUsingGET
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: databaseId
          in: path
          description: databaseId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolEmployeesDto'
  '/scan-solution/databases/{databaseId}/organizations':
    get:
      tags:
        - scan-sol-controller
      summary: getOrganizationsByDatabase
      operationId: getOrganizationsByDatabaseUsingGET
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: databaseId
          in: path
          description: databaseId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolOrganizationsDto'
  '/scan-solution/documents/{documentId}/delete':
    delete:
      tags:
        - scan-sol-controller
      summary: deleteDocument
      operationId: deleteDocumentUsingDELETE
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: documentId
          in: path
          description: documentId
          required: true
          type: integer
          format: int64
        - name: couldBeRestored
          in: query
          description: couldBeRestored
          required: false
          type: boolean
          default: false
      responses:
        '200':
          description: OK
  '/scan-solution/documents/{documentId}/preview':
    post:
      tags:
        - scan-sol-controller
      summary: previewDocument
      operationId: previewDocumentUsingPOST
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: employeeDto
          description: employeeDto
          required: true
          schema:
            $ref: '#/definitions/ScanSolEmployeeFilterRequest'
        - name: documentId
          in: path
          description: documentId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
  '/scan-solution/documents/{documentId}/restore':
    post:
      tags:
        - scan-sol-controller
      summary: restoreDocument
      operationId: restoreDocumentUsingPOST
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: documentId
          in: path
          description: documentId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
  '/scan-solution/documents/{documentId}/update':
    post:
      tags:
        - scan-sol-controller
      summary: updateDocument
      operationId: updateDocumentUsingPOST
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: documentId
          in: path
          description: documentId
          required: true
          type: integer
          format: int64
        - in: body
          name: updateDocumentRequest
          description: updateDocumentRequest
          required: true
          schema:
            $ref: '#/definitions/UpdateDocumentRequest'
      responses:
        '200':
          description: OK
  /scan-solution/employees:
    post:
      tags:
        - scan-sol-controller
      summary: authEmployee
      operationId: authEmployeeUsingPOST
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: authRequest
          description: authRequest
          required: true
          schema:
            $ref: '#/definitions/ScanSolEmployeeAuthRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolEmployeeInfoDto'
  '/scan-solution/employees/{employeeId}/organizations':
    get:
      tags:
        - scan-sol-controller
      summary: getOrganizationsByEmployee
      operationId: getOrganizationsByEmployeeUsingGET
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: employeeId
          in: path
          description: employeeId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolIdsDto'
  '/scan-solution/organizations/{organizationId}/details':
    get:
      tags:
        - scan-sol-controller
      summary: getOrganizationDetails
      operationId: getOrganizationDetailsUsingGET
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: organizationId
          in: path
          description: organizationId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolOrganizationDto'
  '/scan-solution/organizations/{organizationId}/residents':
    get:
      tags:
        - scan-sol-controller
      summary: getResidentsByOrganization
      operationId: getResidentsByOrganizationUsingGET
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: organizationId
          in: path
          description: organizationId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolResidentsDto'
  '/scan-solution/residents/{residentId}/documents':
    post:
      tags:
        - scan-sol-controller
      summary: getResidentDocuments
      operationId: getResidentDocumentsUsingPOST
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: employeeDto
          description: employeeDto
          required: true
          schema:
            $ref: '#/definitions/ScanSolEmployeeFilterRequest'
        - name: residentId
          in: path
          description: residentId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ScanSolDocumentsDto'
  '/scan-solution/residents/{residentId}/documents/upload':
    post:
      tags:
        - scan-sol-controller
      summary: uploadDocument
      operationId: uploadDocumentUsingPOST
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: uploadDocument
          description: uploadDocument
          required: true
          schema:
            $ref: '#/definitions/ScanSolUploadDocumentRequest'
        - name: residentId
          in: path
          description: residentId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: integer
            format: int64
definitions:
  ScanSolBaseEmployeeInfoDto:
    type: object
    properties:
      firstName:
        type: string
      id:
        type: integer
        format: int64
      inactive:
        type: string
      lastName:
        type: string
      login:
        type: string
      name:
        type: string
  ScanSolDatabaseDto:
    type: object
    properties:
      companyCode:
        type: string
      id:
        type: integer
        format: int64
      name:
        type: string
  ScanSolDatabasesDto:
    type: object
    properties:
      companies:
        type: array
        items:
          $ref: '#/definitions/ScanSolDatabaseDto'
  ScanSolDocumentDto:
    type: object
    properties:
      author:
        $ref: '#/definitions/ScanSolBaseEmployeeInfoDto'
      creationTime:
        type: string
      id:
        type: integer
        format: int64
      length:
        type: string
      mimeType:
        type: string
      originalName:
        type: string
      shared:
        type: boolean
      title:
        type: string
      visible:
        type: boolean
  ScanSolDocumentsDto:
    type: object
    properties:
      documents:
        type: array
        items:
          $ref: '#/definitions/ScanSolDocumentDto'
  ScanSolEmployeeAuthRequest:
    type: object
    properties:
      companyId:
        type: string
      login:
        type: string
      pwd:
        type: string
  ScanSolEmployeeFilterRequest:
    type: object
    properties:
      employeeId:
        type: integer
        format: int64
  ScanSolEmployeeInfoDto:
    type: object
    properties:
      communities:
        type: array
        items:
          $ref: '#/definitions/ScanSolOrganizationDto'
      company:
        $ref: '#/definitions/ScanSolDatabaseDto'
      employee:
        $ref: '#/definitions/ScanSolBaseEmployeeInfoDto'
      roles:
        type: array
        items:
          $ref: '#/definitions/ScanSolRoleDto'
  ScanSolEmployeesDto:
    type: object
    properties:
      employees:
        type: array
        items:
          $ref: '#/definitions/ScanSolBaseEmployeeInfoDto'
  ScanSolIdsDto:
    type: object
    properties:
      ids:
        type: array
        items:
          type: integer
          format: int64
  ScanSolOrganizationDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      isArchived:
        type: boolean
      legacyId:
        type: string
      moduleHie:
        type: boolean
      name:
        type: string
  ScanSolOrganizationsDto:
    type: object
    properties:
      communities:
        type: array
        items:
          $ref: '#/definitions/ScanSolOrganizationDto'
  ScanSolResidentDto:
    type: object
    properties:
      birthDate:
        type: string
      firstName:
        type: string
      id:
        type: integer
        format: int64
      inactive:
        type: boolean
      lastName:
        type: string
      legacyId:
        type: string
      middleName:
        type: string
      preferredName:
        type: string
      ssn:
        type: string
  ScanSolResidentsDto:
    type: object
    properties:
      residents:
        type: array
        items:
          $ref: '#/definitions/ScanSolResidentDto'
  ScanSolRoleDto:
    type: object
    properties:
      name:
        type: string
  ScanSolUploadDocumentRequest:
    type: object
    properties:
      content:
        type: string
        format: byte
      employeeId:
        type: integer
        format: int64
      mimeType:
        type: string
      originalName:
        type: string
      shared:
        type: boolean
      title:
        type: string
  UpdateDocumentRequest:
    type: object
    properties:
      employeeId:
        type: integer
        format: int64
      shared:
        type: boolean
      title:
        type: string
